name: PC Virtual Gratis

on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Configure RDP
        run: |
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -name "fDenyTSConnections" -Value 0
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
          net user runneradmin Pass123456789! /add
          net localgroup administrators runneradmin /add

      - name: Install and Start Ngrok
        run: |
          choco install ngrok -y
          ngrok config add-authtoken 3KPPikjdFCBQHvFklLkbQUmnaip_4keERrEFKjto1jC7e9y9r
          Start-Process powershell -ArgumentList '-NoExit -Command "ngrok tcp 3389"'
          Start-Sleep -Seconds 10
          $url = (Invoke-RestMethod -Uri "http://127.0.0.1:4040/api/tunnels").tunnels[0].public_url
          Write-Host "=========================================="
          Write-Host "IP KET NOI RDP CUA BAN LA: $url"
          Write-Host "USER: runneradmin"
          Write-Host "PASS: Pass123456789!"
          Write-Host "=========================================="
          Start-Sleep -Seconds 21600
          
