name: PC Virtual Gratis

on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Configure RDP
        run: |
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -name "fDenyTSConnections" -Value 0
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
          net user runneradmin Pass123456789! /add
          net localgroup administrators runneradmin /add

      - name: Start Ngrok Tunnel
        uses: alx361/ngrok-action@v1
        with:
          token: 3KPPikjdFCBQHvFklLkbQUmnaip_4keERrEFKjto1jC7e9y9r
          port: 3389
          proto: tcp
          
