name: PC Virtual Gratis

on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Preparing Environment
        run: |
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -name "fDenyTSConnections" -Value 0
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
      - name: Download & Setup Ngrok
        run: |
          Invoke-WebRequest https://bin.equinox.io/c/bTsL2vyEMW9/ngrok-v3-stable-windows-amd64.zip -OutFile ngrok.zip
          Expand-Archive ngrok.zip
          .\ngrok\ngrok.exe config add-authtoken 3KPPikjdFCBQHvFklLkbQUmnaip_4keERrEFKjto1jC7e9y9r
      - name: Start RDP Tunnel
        run: |
          Start-Process Powershell -ArgumentList '-Noexit -Command ".\ngrok\ngrok.exe tcp 3389"'
          $host.ui.RawUI.Sleep(21600)
          
